(defparameter *objects* ())
(defparameter *object-locations* ())

(defmacro new-object (loc lst)
  (let ((objs *objects*))
    (cond
      ((= 1 (list-length lst))
        (format t "test")
        (push (car lst) objs)
        (setq *objects* objs)
      )
      ((listp lst)
        (format t "~D" (list-length (cdr lst)))
        (push (car lst) objs)
        (setq *objects* objs)
        (new-object loc (cdr lst))
      )
    )
  )
)

(new-object garden (raisin braisin))
