#!/bin/bash
total=0;
avr=0;
count=0;
while IFS='' read -r line || [[ -n "$line" ]]; do
    total=$(perl -e "print $total + $line") 
    count=$(perl -e "print $count + 1")
    avr=$(perl -e "print $total / $count")
    echo $avr
done < "$1"
